# Generated by Django 3.0.5 on 2020-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_name',
        ),
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
