"""
Django settings for ijin_game project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from django.conf.global_settings import DATETIME_INPUT_FORMATS

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y+ja*_r!^e-jza_3c+d4y=s_6%y$%a#u5ex*ib^n9ulx2-!2e%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'ijin_game_app',  # アプリを追加
    'ijin_game_api',  # rest_apiアプリを追加
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # restを使用できるようにする
    'django_filters',  # django_filtersを使用できるようにする
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ijin_game.urls'

AUTH_USER_MODEL = 'ijin_game_app.Member'  # 認証ユーザモデルを指定
LOGIN_URL = '/accounts/login/'  # 未ログイン状態でのリダイレクト先
LOGIN_REDIRECT_URL = '/mypage'  # ログイン認証後のリダイレクト先
LOGOUT_REDIRECT_URL = '/'  # ログアウト後のリダイレクト先

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # templateを格納するフォルダを指定
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ijin_game.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        # MySQLを使用するための設定
        'ENGINE': 'django.db.backends.mysql',  # mySQLをDBとして使用
        'NAME': 'ijin_db',  # MySQLで作成したデータベース名
        'USER': 'ijin_game',  # データベースに接続するユーザ名
        'PASSWORD': 'PythonStartLab%1',  # データベースに接続するユーザ名のパスワード
        'HOST': 'localhost',  # 接続するホスト(ローカルで動作させる場合はlocalhost)
        'PORT': '3306',  # ポート番号(MySQLは3306がデフォルトポート番号)
        'OPTIONS': {
            'charset': 'utf8mb4',  # MySQL5.7で日本語を扱えるようにする指定
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ja'  # 言語指定を日本語に変更

TIME_ZONE = 'Asia/Tokyo'  # TimeZoneを日本標準時に変更

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATETIME_INPUT_FORMATS += ('%Y/%m/%d',)  # 日付フォーマットに「yyyy/MM/dd」形式を追加

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),  # CSSを格納するフォルダを指定
)

# 画像を扱うフォルダを指定
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
